pipeline {
    agent {
        kubernetes {
            yamlFile "app/jenkins-agent.yaml"
        }
    } 
    stages {
        stage('echo') {
            steps {
              container('docker') {
                echo 'hello world'
                sh 'docker build -t node/sample-web-app .'
                sh 'docker images'
              }
            }
        }
    }
}
