pipeline {
    agent {
        kubernetes {
            yamlFile "app/jenkins-agent.yaml"
        }
    } 
    stages {
        stage('echo') {
            steps {
              container('kaniko') {
                echo 'hello world'
                sh 'executor -c app --insecure -d harbor.localhost:5000/docker/node-app:latest'
              }
            }
        }
    }
}
