pipeline {
    agent {
        kubernetes {
            yamlFile "app/jenkins-agent.yaml"
        }
    } 
    stages {
        stage('echo') {
            steps {
              container('node') {
                echo 'hello world'
              }
            }
        }
    }
}
