name: Rode Policy

on:
  push:

jobs:
  policy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: OPA format
        uses: docker://openpolicyagent/opa:0.24.0-debug
        with:
          entrypoint: sh -c |
            echo "Checking formatting"
            test -z "$(opa fmt -l policies)"
            echo "Running Rego tests"
            opa test -v policies
